### ISSUE TITLE
Blackguard Bulls Strength Stacks

### ISSUE THREAD

**Issue by Yazkir** [urothis/nwn-module-DungeonEternalX#10]
Blackguard bulls strength stacks when you cast it. It's supposed to give X ab per level. So, my 22 bg can get +6 ab from one casting. However, if you cast it back to back, it will give +12 ab instead. 3x will be +15.

**Comment by urothis** [comment]
adeb65c9016442ab28a1314ccfd941ceb6524c49 corrects the stacking issue.
